"use client";
import {useMemo,useRef,useState} from "react";
import {AlertTriangle,CheckCircle2,Download,FileSpreadsheet,FileText,GraduationCap,Loader2,RefreshCw,UploadCloud} from "lucide-react";
import * as XLSX from "xlsx";

type Template={name:string,buffer:ArrayBuffer,sheetName:string,headerRow:number,headers:string[]};
type Decision={file:string,id:string,date:string,type:string,major:string,className:string,station:string,students:number|null,groups:Record<string,number>,note:string};
type OcrWorker={recognize:(image:HTMLCanvasElement)=>Promise<{data:{text:string}}>;terminate:()=>Promise<unknown>};
const MONTHS:Record<string,number>={"ĐH (1)":25,"CĐ (2)":25,"TC (3)":37,"CĐKN (4)":25,"TCKN (5)":37,"THPT (6)":49};
const clean=(v:unknown)=>String(v??"").replace(/\s+/g," ").trim();
const norm=(v:string)=>v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/đ/g,"d").toLowerCase().replace(/[^a-z0-9]/g,"");
function addMonths(value:string,months:number){const m=value.match(/(\d{1,2})[\/\-.](\d{1,2})[\/\-.](\d{4})/);if(!m)return "";const day=+m[1],month=+m[2]-1,year=+m[3],target=month+months,last=new Date(Date.UTC(year,target+1,0)).getUTCDate();return new Date(Date.UTC(year,target,Math.min(day,last)))}
function firstMatch(text:string,patterns:RegExp|RegExp[]){for(const p of Array.isArray(patterns)?patterns:[patterns]){const m=text.match(p);if(m?.[1])return clean(m[1])}return ""}
function textFromPdfItems(items:unknown[]){let out="",lastY:number|null=null;for(const raw of items){const item=raw as {str?:string;transform?:number[]};if(typeof item.str!=="string"||!item.str)continue;const y:number=typeof item.transform?.[5]==="number"?item.transform[5]:(lastY===null?0:lastY);if(lastY!==null&&Math.abs(y-lastY)>2)out+="\n";else if(out&&!out.endsWith("\n"))out+=" ";out+=item.str;lastY=y}return out}
function inferHeader(rows:unknown[][]){let best=0,score=-1;rows.slice(0,40).forEach((r,i)=>{const filled=r.filter(v=>clean(v)).length,words=r.filter(v=>/[A-Za-zÀ-ỹ]/.test(clean(v))).length,s=filled+words*1.5;if(filled>=2&&s>score){best=i;score=s}});return best}
function groupCounts(text:string,total:number|null){const out:Record<string,number>={};for(const raw of text.split(/\n+/)){const s=norm(raw);let key="";if(s.endsWith("thpt")&&!s.includes("doituongtuyensinh"))key="THPT (6)";else if(s.includes("trungcapdung"))key="TC (3)";else if(s.includes("trungcapkhac"))key="TCKN (5)";else if(s.includes("caodangdung"))key="CĐ (2)";else if(s.includes("caodangkhac"))key="CĐKN (4)";else if(s.includes("daihoc")&&s.includes("khac"))key="ĐH (1)";if(key)out[key]=(out[key]||0)+1}const sum=Object.values(out).reduce((a,b)=>a+b,0);if(total&&sum<total&&out["THPT (6)"])out["THPT (6)"]+=total-sum;return out}
function fromFilename(file:string){const id=file.match(/QĐ\s*(\d+)/i)?.[1]||"",d=file.match(/(\d{1,2})[.\-](\d{1,2})[.\-](\d{4})/),students=file.match(/\(\s*(\d+)\s*sv/i)?.[1];return{id:id?`${id}/QĐ-ĐHV`:"",date:d?`${d[1].padStart(2,"0")}/${d[2].padStart(2,"0")}/${d[3]}`:"",students:students?+students:null,type:/\bbs\b|bổ sung/i.test(file)?"Tuyển bổ sung":"Tuyển mới"}}
async function readPdf(file:File,worker:OcrWorker):Promise<Decision[]>{const pdfjs=await import("pdfjs-dist/legacy/build/pdf.mjs");pdfjs.GlobalWorkerOptions.workerSrc=new URL("pdfjs-dist/legacy/build/pdf.worker.min.mjs",import.meta.url).toString();const pdf=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;let text="";for(let i=1;i<=pdf.numPages;i++){const page=await pdf.getPage(i),content=await page.getTextContent();let pageText=textFromPdfItems(content.items);if(clean(pageText).length<30){const viewport=page.getViewport({scale:2}),canvas=document.createElement("canvas"),ctx=canvas.getContext("2d");canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);if(ctx){await page.render({canvas,canvasContext:ctx,viewport}).promise;pageText=(await worker.recognize(canvas)).data.text}}text+="\n"+pageText}const fallback=fromFilename(file.name),id=firstMatch(text,[/S[ốo]\s*:\s*(\d+\s*\/\s*QĐ[-–]ĐHV)/i,/Quy[ếe]t\s*đ[iị]nh\s+s[ốo]\s*(\d+\s*\/\s*QĐ[-–]ĐHV)/i])||fallback.id,dateText=firstMatch(text,[/Ngh[ệe]\s*An\s*,?\s*ng[aà]y\s*(\d{1,2}\s*th[aá]ng\s*\d{1,2}\s*n[aă]m\s*\d{4})/i,/Quy[ếe]t\s*đ[iị]nh[^\n]{0,80}?ng[aà]y\s*(\d{1,2}\s*th[aá]ng\s*\d{1,2}\s*n[aă]m\s*\d{4})/i]),date=dateText?dateText.replace(/\s*th[aá]ng\s*/i,"/").replace(/\s*n[aă]m\s*/i,"/").split("/").map((v,i)=>i<2?v.padStart(2,"0"):v).join("/"):fallback.date,article=firstMatch(text,[/Đi[ềê]u\s*1[^\n]{0,100}?(\d{1,4})\s+th[ií]\s+sinh/i]);const marker=/DANH\s+S[ÁA]CH\s+TH[ÍI]\s+SINH\s+TR[ÚU]NG\s+TUY[ỂE]N/gi,parts=text.split(marker).slice(1),sections=parts.length?parts:[text];return sections.map((section,si)=>{const stated=firstMatch(section,/[ẤA]n\s+đ[iị]nh\s+danh\s+s[aá]ch\s+n[aà]y\s+c[oó]\s+(\d{1,3})\s+ng[ưừ][ờo]i/i),students=stated?+stated:(sections.length===1?fallback.students:null),classLine=firstMatch(section,/[Ll][ớo]p\s+([^\n]{3,120})/i),className=clean(classLine.split(/\.\s*Tr[ưườ]ng/i)[0]),station=firstMatch(section,/(?:C[ơo]\s+s[ởo]\s+ph[ốo]i\s+h[ợo]p|Đ[ơo]n\s+v[iị]\s+li[eê]n\s+k[ếe]t)\s*:\s*([^\n]{3,120})/i),majorRaw=firstMatch(section,/[Nn]g[aà]nh\s+([^,\n]{2,60})/i),round=firstMatch(section,/[ĐD][ỢO]T\s*(\d+)/i),groups=groupCounts(section,students),sum=Object.values(groups).reduce((a,b)=>a+b,0),noteParts=[];if(article&&students&&+article!==students)noteParts.push(`Điều 1: ${article} SV; danh sách này: ${students} SV`);if(students&&sum!==students)noteParts.push(`Cần kiểm tra phân nhóm: nhận diện ${sum}/${students} SV`);return{file:sections.length>1?`${file.name} · danh sách ${si+1}`:file.name,id,date,type:/b[ổo]\s*sung/i.test(text)?`Tuyển bổ sung${round?` đợt ${round}`:""}`:"Tuyển mới",major:/lu[aậ]t/i.test(majorRaw||section)?"Luật học":clean(majorRaw),className,station:clean(station),students,groups,note:noteParts.join(". ")}})}
function fieldKey(header:string){const h=norm(header),tests:[string,string[]][]=[["stt",["stt","tt"]],["major",["nganh","chuyennganh"]],["station",["tram","cosophoihop","diemdatlop"]],["className",["lop","malop"]],["decision",["qdtrungtuyen","soquyetdinh","quyetdinh"]],["decisionDate",["ngayquyetdinh","ngaybanhanh"]],["type",["loaituyen","dottuyen"]],["group",["doituong","nhomdoituong"]],["count",["soluong","sosinhvien"]],["graduation",["thoigiantndukien","thoigiandukientotnghiep","dukientotnghiep"]],["note",["ghichu","luuy"]],["source",["tenfilenguon","filenguon","nguon"]]];for(const[key,aliases]of tests)if(aliases.some(a=>h===a||h.includes(a)))return key;return"unknown"}
function rowValue(header:string,d:Decision,group:string,count:number,index:number){switch(fieldKey(header)){case"stt":return index;case"major":return d.major;case"station":return d.station;case"className":return d.className;case"decision":return`${d.id}${d.date?` ngày ${d.date}`:""}\n${d.type}\nDanh sách tại trạm: ${d.students??0} SV`;case"decisionDate":return addMonths(d.date,0);case"type":return d.type;case"group":return group;case"count":return count;case"graduation":return count>0?addMonths(d.date,MONTHS[group]||0):"";case"note":return d.note;case"source":return d.file;default:return""}}

export default function Home(){
 const[template,setTemplate]=useState<Template|null>(null),[pdfs,setPdfs]=useState<File[]>([]),[decisions,setDecisions]=useState<Decision[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[progress,setProgress]=useState("");const excelRef=useRef<HTMLInputElement>(null),pdfRef=useRef<HTMLInputElement>(null);const total=useMemo(()=>decisions.reduce((sum,d)=>sum+(d.students??Object.values(d.groups).reduce((a,b)=>a+b,0)),0),[decisions]);
 async function chooseExcel(file?:File){if(!file)return;setError("");try{const buffer=await file.arrayBuffer(),wb=XLSX.read(buffer,{type:"array",cellDates:true}),sheetName=wb.SheetNames[0],rows=XLSX.utils.sheet_to_json<unknown[]>(wb.Sheets[sheetName],{header:1,defval:""}),headerRow=inferHeader(rows);setTemplate({name:file.name,buffer,sheetName,headerRow,headers:(rows[headerRow]||[]).map(clean).filter(Boolean)})}catch{setError("Không đọc được file Excel. Cô hãy kiểm tra lại định dạng .xlsx hoặc .xls.")}}
 async function analyze(){if(!template||!pdfs.length)return;setBusy(true);setError("");setProgress("Khởi tạo OCR tiếng Việt...");let worker:OcrWorker|null=null;try{const{createWorker}=await import("tesseract.js");worker=await createWorker("vie");const parsed:Decision[]=[];for(let i=0;i<pdfs.length;i++){setProgress(`Đang đọc quyết định ${i+1}/${pdfs.length}: ${pdfs[i].name}`);parsed.push(...await readPdf(pdfs[i],worker as OcrWorker))}setDecisions(parsed);setProgress(`Đã tách ${parsed.length} danh sách từ ${pdfs.length} quyết định`) }catch(e){setError(`Không thể phân tích PDF: ${e instanceof Error?e.message:"Lỗi không xác định"}`)}finally{if(worker)await worker.terminate();setBusy(false)}}
 function update(index:number,key:keyof Decision,value:string){setDecisions(list=>list.map((d,i)=>i===index?{...d,[key]:key==="students"?(value===""?null:Number(value)):value}:d))}
 function exportExcel(){if(!template||!decisions.length)return;const wb=XLSX.read(template.buffer,{type:"array",cellDates:true}),ws=wb.Sheets[template.sheetName],range=XLSX.utils.decode_range(ws["!ref"]||"A1"),start=template.headerRow+3;for(let r=start;r<=range.e.r;r++)for(let c=0;c<template.headers.length;c++){const a=XLSX.utils.encode_cell({r,c});if(ws[a]){delete ws[a].v;delete ws[a].w;delete ws[a].f;ws[a].t="s"}}ws["!merges"]=(ws["!merges"]||[]).filter(m=>m.e.r<start);let row=start,index=1;for(const d of decisions){const blockStart=row;for(const group of Object.keys(MONTHS)){const count=d.groups[group]||0;template.headers.forEach((h,c)=>{const key=fieldKey(h),repeat=["stt","major","station","className","decision","type","note","source"].includes(key),address=XLSX.utils.encode_cell({r:row,c}),value=repeat&&row>blockStart?"":rowValue(h,d,group,count,index),old=ws[address]||{};ws[address]={...old,v:value,t:value instanceof Date?"d":typeof value==="number"?"n":"s"};if(value instanceof Date)ws[address].z="dd/mm/yyyy"});row++}for(let c=0;c<=5;c++)ws["!merges"].push({s:{r:blockStart,c},e:{r:blockStart+5,c}});index++}const totalRow=row;template.headers.forEach((h,c)=>{const a=XLSX.utils.encode_cell({r:totalRow,c}),key=fieldKey(h),old=ws[a]||{},value=key==="group"?"TỔNG SỐ SINH VIÊN QUẢN LÝ":key==="count"?total:"";ws[a]={...old,v:value,t:typeof value==="number"?"n":"s"}});range.e.r=Math.max(totalRow,range.e.r);range.e.c=Math.max(range.e.c,template.headers.length-1);ws["!ref"]=XLSX.utils.encode_range(range);XLSX.writeFile(wb,`TONG_HOP_${template.name.replace(/\.(xlsx|xls)$/i,"")}.xlsx`,{cellDates:true})}
 function reset(){setTemplate(null);setPdfs([]);setDecisions([]);setError("")}
 return <main className="min-h-screen bg-[#f2f7fb] text-[#173b5d]"><header className="border-b border-[#d9e6f0] bg-white"><div className="mx-auto flex h-18 max-w-[1500px] items-center gap-3 px-4 sm:px-7"><span className="grid h-11 w-11 place-items-center rounded-xl bg-[#0d62ad] text-white shadow-lg"><GraduationCap/></span><div><h1 className="text-xl font-extrabold text-[#123f6b]">HPOLC</h1><p className="text-sm text-[#71879a]">Tổng hợp dữ liệu đào tạo</p></div><button onClick={reset} className="ml-auto inline-flex items-center gap-2 rounded-xl border px-3 py-2 text-sm font-semibold text-[#557189]"><RefreshCw size={16}/> Làm mới</button></div></header><div className="mx-auto max-w-[1500px] p-4 sm:p-7">
  <section className="mb-5"><h2 className="text-2xl font-extrabold sm:text-3xl">Tạo bảng tổng hợp theo file mẫu</h2><p className="mt-2 max-w-3xl text-[#657e94]">Hệ thống giữ nguyên cấu trúc Excel, nhận diện tên cột và đưa dữ liệu từ các quyết định vào đúng trường tương ứng.</p></section>
  {error&&<div className="mb-4 flex items-start gap-2 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700"><AlertTriangle className="shrink-0" size={18}/>{error}</div>}
  <section className="grid gap-4 lg:grid-cols-3"><UploadBox step="1" title="Chọn file Excel mẫu" text={template?template.name:"File .xlsx hoặc .xls bất kỳ"} icon={<FileSpreadsheet/>} active={!!template} onClick={()=>excelRef.current?.click()}/><UploadBox step="2" title="Chọn các quyết định" text={pdfs.length?`${pdfs.length} file PDF đã chọn`:"Có thể chọn nhiều PDF cùng lúc"} icon={<FileText/>} active={pdfs.length>0} onClick={()=>pdfRef.current?.click()}/><div className="rounded-2xl bg-gradient-to-br from-[#0f5da5] to-[#087d9f] p-5 text-white shadow-lg"><p className="text-sm font-bold text-blue-100">BƯỚC 3</p><h3 className="mt-2 text-lg font-extrabold">Phân tích và đối chiếu</h3><p className="mt-1 min-h-10 text-sm text-blue-100">{busy?progress:"Đọc cả PDF có chữ và PDF scan ảnh."}</p><button onClick={analyze} disabled={!template||!pdfs.length||busy} className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-white px-4 py-3 font-bold text-[#0e5d9f] disabled:opacity-50">{busy?<Loader2 className="animate-spin" size={18}/>:<UploadCloud size={18}/>} {busy?"Đang OCR và phân tích...":"Phân tích dữ liệu"}</button></div></section>
  <input ref={excelRef} hidden type="file" accept=".xlsx,.xls" onChange={e=>chooseExcel(e.target.files?.[0])}/><input ref={pdfRef} hidden type="file" accept="application/pdf" multiple onChange={e=>{setPdfs(Array.from(e.target.files||[]));setDecisions([])}}/>
  {template&&<section className="mt-5 rounded-2xl border bg-white p-5 shadow-sm"><div className="flex items-center justify-between gap-3"><div><h3 className="font-extrabold">Các cột đã nhận diện trong file mẫu</h3><p className="mt-1 text-sm text-[#70869a]">Trang tính: {template.sheetName} · Dòng tiêu đề: {template.headerRow+1} · {template.headers.length} cột</p></div><CheckCircle2 className="text-emerald-600"/></div><div className="mt-4 flex flex-wrap gap-2">{template.headers.map((h,i)=><span key={i} className={`rounded-lg border px-2.5 py-1.5 text-sm ${fieldKey(h)==="unknown"?"border-amber-200 bg-amber-50 text-amber-800":"border-blue-100 bg-blue-50 text-blue-800"}`}>{h}{fieldKey(h)==="unknown"&&" · giữ trống"}</span>)}</div></section>}
  {decisions.length>0&&<section className="mt-5 overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-5"><div><h3 className="text-lg font-extrabold">Kết quả nhận diện</h3><p className="text-sm text-[#6d8397]">{pdfs.length} quyết định · {decisions.length} danh sách/lớp · khoảng {total} người. Cô có thể sửa trực tiếp trước khi xuất.</p></div><button onClick={exportExcel} className="inline-flex items-center gap-2 rounded-xl bg-[#0d62ad] px-4 py-2.5 font-bold text-white"><Download size={18}/> Xuất theo file mẫu</button></div><div className="overflow-x-auto"><table className="w-full min-w-[1050px] text-sm"><thead className="bg-[#f4f8fb] text-left text-[#607b91]"><tr><th className="p-3">File nguồn</th><th>Số quyết định</th><th>Ngày ban hành</th><th>Loại tuyển</th><th>Ngành</th><th>Lớp</th><th>Số người</th><th>Nhóm đã nhận diện</th></tr></thead><tbody className="divide-y">{decisions.map((d,i)=><tr key={d.file}><td className="max-w-48 p-3 font-semibold"><span className="block truncate">{d.file}</span>{d.note&&<span className="mt-1 block text-xs text-amber-700">{d.note}</span>}</td><Edit value={d.id} onChange={v=>update(i,"id",v)}/><Edit value={d.date} onChange={v=>update(i,"date",v)} placeholder="dd/mm/yyyy"/><Edit value={d.type} onChange={v=>update(i,"type",v)}/><Edit value={d.major} onChange={v=>update(i,"major",v)}/><Edit value={d.className} onChange={v=>update(i,"className",v)}/><Edit value={d.students??""} onChange={v=>update(i,"students",v)}/><td className="min-w-56 p-2 text-xs">{Object.entries(d.groups).length?Object.entries(d.groups).map(([g,n])=><span key={g} className="mr-1 inline-block rounded bg-emerald-50 px-2 py-1 text-emerald-800">{g}: {n}</span>):<span className="text-amber-700">Chưa nhận diện nhóm</span>}</td></tr>)}</tbody></table></div></section>}
  <div className="mt-5 rounded-xl border border-blue-100 bg-blue-50 p-4 text-sm leading-6 text-[#496b87]"><b>Lưu ý:</b> PDF có lớp chữ được đọc tự động. Quyết định scan ảnh sẽ được đánh dấu để nhập tay hoặc xử lý OCR. Các cột chưa nhận diện vẫn được giữ nguyên và không bị xóa.</div>
 </div></main>}
function UploadBox({step,title,text,icon,active,onClick}:{step:string,title:string,text:string,icon:React.ReactNode,active:boolean,onClick:()=>void}){return <button onClick={onClick} className={`min-h-48 rounded-2xl border-2 border-dashed p-5 text-left transition ${active?"border-emerald-300 bg-emerald-50":"border-[#bfd2e1] bg-white hover:border-[#0d62ad]"}`}><div className="flex items-start justify-between"><span className={`grid h-12 w-12 place-items-center rounded-xl ${active?"bg-emerald-100 text-emerald-700":"bg-blue-50 text-[#0d62ad]"}`}>{icon}</span>{active?<CheckCircle2 className="text-emerald-600"/>:<span className="rounded-full bg-[#eef4f8] px-2.5 py-1 text-xs font-bold">BƯỚC {step}</span>}</div><h3 className="mt-4 font-extrabold">{title}</h3><p className="mt-1 break-all text-sm text-[#70869a]">{text}</p></button>}
function Edit({value,onChange,placeholder}:{value:string|number,onChange:(v:string)=>void,placeholder?:string}){return <td className="p-2"><input value={value} placeholder={placeholder} onChange={e=>onChange(e.target.value)} className="min-w-28 rounded-lg border border-[#d6e2ec] px-2.5 py-2 outline-none focus:border-[#0d62ad]"/></td>}
