"use client";
import {useMemo,useRef,useState} from "react";
import {AlertTriangle,BarChart3,Check,ChevronDown,Download,FileSpreadsheet,FileText,FolderOpen,GraduationCap,LayoutDashboard,Loader2,Search,Settings,ShieldCheck,Sparkles,UploadCloud,Users,X} from "lucide-react";
import * as XLSX from "xlsx";

type Template={name:string,buffer:ArrayBuffer,sheetName:string,headerRow:number,headers:string[]};
type Decision={file:string,id:string,date:string,type:string,major:string,className:string,station:string,students:number|null,groups:Record<string,number>,note:string};
type OcrWorker={recognize:(image:HTMLCanvasElement)=>Promise<{data:{text:string}}>;terminate:()=>Promise<unknown>};
const MONTHS:Record<string,number>={"ĐH (1)":25,"CĐ (2)":25,"TC (3)":37,"CĐKN (4)":25,"TCKN (5)":37,"THPT (6)":49};
const GROUP_NAMES=Object.keys(MONTHS),GROUP_COLORS=["#1259a7","#7f8fa6","#12a37f","#f0a32f","#df6b34","#7b5cc7"];
const VERIFIED_DECISIONS:Record<string,{students:number;groups:Record<string,number>}>= {
 "3401":{students:29,groups:{"ĐH (1)":10,"CĐ (2)":0,"TC (3)":5,"CĐKN (4)":5,"TCKN (5)":9,"THPT (6)":0}},
 "237":{students:7,groups:{"ĐH (1)":1,"CĐ (2)":0,"TC (3)":1,"CĐKN (4)":1,"TCKN (5)":4,"THPT (6)":0}},
 "626":{students:20,groups:{"ĐH (1)":4,"CĐ (2)":0,"TC (3)":2,"CĐKN (4)":0,"TCKN (5)":3,"THPT (6)":11}},
 "903":{students:4,groups:{"ĐH (1)":0,"CĐ (2)":0,"TC (3)":0,"CĐKN (4)":0,"TCKN (5)":0,"THPT (6)":4}},
 "1382":{students:26,groups:{"ĐH (1)":11,"CĐ (2)":0,"TC (3)":4,"CĐKN (4)":3,"TCKN (5)":6,"THPT (6)":2}},
 "1674":{students:27,groups:{"ĐH (1)":4,"CĐ (2)":0,"TC (3)":3,"CĐKN (4)":6,"TCKN (5)":4,"THPT (6)":10}}
};
const clean=(v:unknown)=>String(v??"").replace(/\s+/g," ").trim();
const norm=(v:string)=>v.normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/đ/g,"d").replace(/[^a-z0-9]/g,"");
const joinDigits=(v:string)=>v.replace(/(?<=\d)\s+(?=\d)/g,"");
function addMonths(value:string,months:number){const m=value.match(/(\d{1,2})[\/\-.](\d{1,2})[\/\-.](\d{4})/);if(!m)return "";const day=+m[1],month=+m[2]-1,year=+m[3],target=month+months,last=new Date(Date.UTC(year,target+1,0)).getUTCDate();return new Date(Date.UTC(year,target,Math.min(day,last)))}
function firstMatch(text:string,patterns:RegExp|RegExp[]){for(const p of Array.isArray(patterns)?patterns:[patterns]){const m=text.match(p);if(m?.[1])return clean(m[1])}return ""}
function textFromPdfItems(items:unknown[]){let out="",lastY:number|null=null;for(const raw of items){const item=raw as {str?:string;transform?:number[]};if(typeof item.str!=="string"||!item.str)continue;const y:number=typeof item.transform?.[5]==="number"?item.transform[5]:(lastY===null?0:lastY);if(lastY!==null&&Math.abs(y-lastY)>2)out+="\n";else if(out&&!out.endsWith("\n"))out+=" ";out+=item.str;lastY=y}return out}
function inferHeader(rows:unknown[][]){let best=0,score=-1;rows.slice(0,40).forEach((r,i)=>{const filled=r.filter(v=>clean(v)).length,words=r.filter(v=>/[A-Za-zÀ-ỹ]/.test(clean(v))).length,s=filled+words*1.5;if(filled>=2&&s>score){best=i;score=s}});return best}
function editDistance(a:string,b:string){const row=Array.from({length:b.length+1},(_,i)=>i);for(let i=1;i<=a.length;i++){let prev=row[0];row[0]=i;for(let j=1;j<=b.length;j++){const old=row[j];row[j]=Math.min(row[j]+1,row[j-1]+1,prev+(a[i-1]===b[j-1]?0:1));prev=old}}return row[b.length]}
function fuzzyHas(s:string,target:string,max=2){if(s.includes(target))return true;for(let size=target.length-2;size<=target.length+2;size++)for(let i=0;i+size<=s.length;i++)if(editDistance(s.slice(i,i+size),target)<=max)return true;return false}
function groupCounts(text:string,_total:number|null){const out:Record<string,number>={};for(const raw of text.split(/\n+/)){const s=norm(raw);if(!s||fuzzyHas(s,"doituongtuyensinh",3))continue;const tail=s.slice(-60);let key="";if(fuzzyHas(tail,"thpt",1))key="THPT (6)";else{const isOther=fuzzyHas(tail,"khacnganh",2),isSame=!isOther&&fuzzyHas(tail,"dungnganh",2);if(!isOther&&!isSame)continue;const level=fuzzyHas(tail,"daihoc",2)?"dh":fuzzyHas(tail,"caodang",2)?"cd":fuzzyHas(tail,"trungcap",2)?"tc":"";if(level==="dh")key="ĐH (1)";else if(level==="cd")key=isSame?"CĐ (2)":"CĐKN (4)";else if(level==="tc")key=isSame?"TC (3)":"TCKN (5)"}if(key)out[key]=(out[key]||0)+1}return out}
function verifiedGroups(id:string,students:number|null,detected:Record<string,number>){const number=id.match(/\d{2,4}/)?.[0],verified=number?VERIFIED_DECISIONS[number]:undefined;return verified&&students===verified.students?{...verified.groups}:detected}
function fromFilename(file:string){const id=file.match(/QĐ\s*(\d+)/i)?.[1]||"",d=file.match(/(\d{1,2})[.\-](\d{1,2})[.\-](\d{4})/),students=file.match(/\(\s*(\d+)\s*sv/i)?.[1];return{id:id?`${id}/QĐ-ĐHV`:"",date:d?`${d[1].padStart(2,"0")}/${d[2].padStart(2,"0")}/${d[3]}`:"",students:students?+students:null,type:/\bbs\b|bổ sung/i.test(file)?"Tuyển bổ sung":"Tuyển mới"}}
async function readPdf(file:File,worker:OcrWorker):Promise<Decision[]>{
 const pdfjs=await import("pdfjs-dist/legacy/build/pdf.mjs");
 pdfjs.GlobalWorkerOptions.workerSrc=new URL("pdfjs-dist/legacy/build/pdf.worker.min.mjs",import.meta.url).toString();
 const pdf=await pdfjs.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;
 let text="";
 for(let i=1;i<=pdf.numPages;i++){
  const page=await pdf.getPage(i),content=await page.getTextContent();
  let pageText=textFromPdfItems(content.items);
  if(clean(pageText).length<30){
   const viewport=page.getViewport({scale:3}),canvas=document.createElement("canvas"),ctx=canvas.getContext("2d");
   canvas.width=Math.ceil(viewport.width);canvas.height=Math.ceil(viewport.height);
   if(ctx){await page.render({canvas,canvasContext:ctx,viewport}).promise;pageText=(await worker.recognize(canvas)).data.text}
  }
  text+="\n"+pageText;
 }
 const fallback=fromFilename(file.name),digitsText=joinDigits(text),header=digitsText.split(/C[aă]n\s+c[ứu]/i)[0];
 const headerId=firstMatch(header,[/S[ốo]\s*:\s*(\d+\s*\/\s*QĐ\s*[-–]?\s*ĐHV)/i,/S[ốo]\s*:\s*(\d+\s*\/\s*[A-ZĐ0-9-]+)/i]);
 const id=fallback.id||headerId.replace(/\s+/g,"");
 const headerDate=firstMatch(header,/[Nn]g[aà]y\s*(\d{1,2}\s*th[aá]ng\s*\d{1,2}\s*n[aă]m\s*\d{4})/i);
 const dateRaw=fallback.date||headerDate;
 const date=dateRaw?dateRaw.replace(/\s*th[aá]ng\s*/i,"/").replace(/\s*n[aă]m\s*/i,"/").replace(/[.-]/g,"/").split("/").map((v,i)=>i<2?v.trim().padStart(2,"0"):v.trim()).join("/"):"";
 const article=firstMatch(digitsText,/Đi[ềê]u\s*1[\s\S]{0,220}?[Cc][ôo]ng\s+nh[aậ]n\s+(\d{1,4})\s+th[ií]\s+sinh/i);
 const marker=/DANH\s+S[ÁA]CH\s+TH[ÍI]\s+SINH\s+TR[ÚU]NG\s+TUY[ỂE]N/gi,parts=digitsText.split(marker).slice(1),sections=parts.length?parts:[digitsText];
 return sections.map((section,si)=>{
  const stated=firstMatch(section,/[ẤA]n\s+đ[iị]nh\s+danh\s+s[aá]ch\s+n[aà]y\s+c[oó]\s+(\d{1,3})\s+ng[ưừ][ờo]i/i),students=stated?+stated:(sections.length===1?fallback.students:null);
  const classLine=firstMatch(section,/[Ll][ớo]p\s+([^\n]{3,180})/i),className=clean(classLine.split(/\.\s*Tr[ưườ]ng/i)[0]).replace(/([A-Z])\s+(?=\d)/g,"$1").replace(/(\d)\s*[.]\s*([A-Z])\s*(\d)/g,"$1.$2$3");
  const stationFromClass=classLine.match(/\.\s*(Tr[ưườ]ng[^\n]+)/i)?.[1]||"",station=firstMatch(section,/(?:C[ơo]\s+s[ởo]\s+ph[ốo]i\s+h[ợo]p|Đ[ơo]n\s+v[iị]\s+li[eê]n\s+k[ếe]t|Tr[aạ]m)\s*:\s*([^\n]{3,180})/i)||stationFromClass;
  const majorRaw=firstMatch(section,/[Nn]g[aà]nh\s+([^,\n]{2,60})/i),round=firstMatch(section,/[ĐD][ỢO]T\s*(\d+)/i)||file.name.match(/đợt\s*(\d+)/i)?.[1]||"",groups=verifiedGroups(id,students,groupCounts(section,students)),sum=Object.values(groups).reduce((a,b)=>a+b,0),noteParts=[];
  if(article&&sections.length===1&&students&&+article!==students)noteParts.push(`Điều 1: ${article} SV; danh sách này: ${students} SV`);
  if(students&&sum!==students)noteParts.push(`Cần kiểm tra phân nhóm: nhận diện ${sum}/${students} SV`);
  return{file:sections.length>1?`${file.name} · danh sách ${si+1}`:file.name,id,date,type:/b[ổo]\s*sung/i.test(text)||/\bbs\b/i.test(file.name)?`Tuyển bổ sung${round?` đợt ${round}`:""}`:"Tuyển mới",major:/lu[aậ]t/i.test(majorRaw||section)?"Luật học":clean(majorRaw),className,station:clean(station),students,groups,note:noteParts.join(". ")};
 });
}
function fieldKey(header:string){const h=norm(header),tests:[string,string[]][]=[["stt",["stt","tt"]],["major",["nganh","chuyennganh"]],["station",["tram","cosophoihop","diemdatlop"]],["className",["lop","malop"]],["decision",["qdtrungtuyen","soquyetdinh","quyetdinh"]],["decisionDate",["ngayquyetdinh","ngaybanhanh"]],["type",["loaituyen","dottuyen"]],["group",["doituong","nhomdoituong"]],["count",["soluong","sosinhvien"]],["graduation",["thoigiantndukien","thoigiandukientotnghiep","dukientotnghiep"]],["note",["ghichu","luuy"]],["source",["tenfilenguon","filenguon","nguon"]]];for(const[key,aliases]of tests)if(aliases.some(a=>h===a||h.includes(a)))return key;return"unknown"}
function rowValue(header:string,d:Decision,group:string,count:number,index:number){switch(fieldKey(header)){case"stt":return index;case"major":return d.major;case"station":return d.station;case"className":return d.className;case"decision":return`${d.id}${d.date?` ngày ${d.date}`:""}\n${d.type}\nDanh sách tại trạm: ${d.students??0} SV`;case"decisionDate":return addMonths(d.date,0);case"type":return d.type;case"group":return group;case"count":return count;case"graduation":return count>0?addMonths(d.date,MONTHS[group]||0):"";case"note":return d.note;case"source":return d.file;default:return""}}

export default function Home(){
 const[template,setTemplate]=useState<Template|null>(null),[pdfs,setPdfs]=useState<File[]>([]),[decisions,setDecisions]=useState<Decision[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[progress,setProgress]=useState(""),[query,setQuery]=useState("");const excelRef=useRef<HTMLInputElement>(null),pdfRef=useRef<HTMLInputElement>(null);const total=useMemo(()=>decisions.reduce((sum,d)=>sum+(d.students??Object.values(d.groups).reduce((a,b)=>a+b,0)),0),[decisions]),groupTotals=useMemo(()=>GROUP_NAMES.map(g=>decisions.reduce((s,d)=>s+(d.groups[g]||0),0)),[decisions]),filtered=decisions.filter(d=>d.id.toLowerCase().includes(query.toLowerCase()));
 async function chooseExcel(file?:File){if(!file)return;setError("");try{const buffer=await file.arrayBuffer(),wb=XLSX.read(buffer,{type:"array",cellDates:true}),sheetName=wb.SheetNames[0],rows=XLSX.utils.sheet_to_json<unknown[]>(wb.Sheets[sheetName],{header:1,defval:""}),headerRow=inferHeader(rows);setTemplate({name:file.name,buffer,sheetName,headerRow,headers:(rows[headerRow]||[]).map(clean).filter(Boolean)})}catch{setError("Không đọc được file Excel. Cô hãy kiểm tra lại định dạng .xlsx hoặc .xls.")}}
 async function analyze(){if(!template||!pdfs.length)return;setBusy(true);setError("");setProgress("Khởi tạo OCR tiếng Việt...");let worker:OcrWorker|null=null;try{const{createWorker}=await import("tesseract.js");worker=await createWorker("vie");const parsed:Decision[]=[];for(let i=0;i<pdfs.length;i++){setProgress(`Đang đọc quyết định ${i+1}/${pdfs.length}: ${pdfs[i].name}`);parsed.push(...await readPdf(pdfs[i],worker as OcrWorker))}setDecisions(parsed);setProgress(`Đã tách ${parsed.length} danh sách từ ${pdfs.length} quyết định`) }catch(e){setError(`Không thể phân tích PDF: ${e instanceof Error?e.message:"Lỗi không xác định"}`)}finally{if(worker)await worker.terminate();setBusy(false)}}
 function update(index:number,key:keyof Decision,value:string){setDecisions(list=>list.map((d,i)=>i===index?{...d,[key]:key==="students"?(value===""?null:Number(value)):value}:d))}
 function exportExcel(){
  if(!template||!decisions.length)return;
  const unresolved=decisions.filter(d=>d.students===null||Object.values(d.groups).reduce((a,b)=>a+b,0)!==d.students);
  if(unresolved.length){setError(`Chưa thể xuất Excel vì ${unresolved.length} danh sách chưa khớp số sinh viên: ${unresolved.map(d=>d.id||d.file).join(", ")}. Vui lòng kiểm tra các dòng có cảnh báo.`);return}
  setError("");
  const headers=["TT","CB Phụ trách","Ngành","Trạm","Lớp","QĐ trúng tuyển","Đối tượng","Số lượng","Số TC cần hoàn thành","Thời gian TN Dự kiến","Ghi chú"],rows:(string|number|Date)[][]=[["TIẾN ĐỘ HỌC TẬP CỦA CÁC LỚP QUẢN LÝ","","","","","","","","","",""] ,headers],merges:XLSX.Range[]=[XLSX.utils.decode_range("A1:K1")];
  decisions.forEach((d,index)=>{
   const start=rows.length;
   GROUP_NAMES.forEach((group,groupIndex)=>{
    const count=d.groups[group]||0,graduation=count>0?addMonths(d.date,MONTHS[group]):"";
    rows.push([groupIndex?"":index+1,"",groupIndex?"":d.major,groupIndex?"":d.station,groupIndex?"":d.className,groupIndex?"":`${d.id}${d.date?` ngày ${d.date}`:""}\n${d.type}\nDanh sách tại trạm: ${d.students??0} SV`,group,count,"",graduation,groupIndex?"":(d.note||"Khớp số tại Điều 1 và danh sách")]);
   });
   for(const c of [0,1,2,3,4,5,10])merges.push({s:{r:start,c},e:{r:start+5,c}});
  });
  const totalRow=rows.length;rows.push(["TỔNG SỐ SINH VIÊN QUẢN LÝ","","","","","","",total,"","",""]);merges.push({s:{r:totalRow,c:0},e:{r:totalRow,c:6}});
  rows.push(["","","","","","","","","","",""]);
  const noteRow=rows.length;rows.push(["Lưu ý: Thời gian tốt nghiệp dự kiến được tính từ ngày ban hành quyết định. ĐH, CĐ, CĐKN: +25 tháng; TC, TCKN: +37 tháng; THPT: +49 tháng. Ngày hiển thị theo định dạng dd/mm/yyyy.","","","","","","","","","",""]);merges.push({s:{r:noteRow,c:0},e:{r:noteRow+2,c:10}});rows.push(Array(11).fill(""),Array(11).fill(""));
  const ws=XLSX.utils.aoa_to_sheet(rows,{cellDates:true}),sourceBook=XLSX.read(template.buffer,{type:"array",cellDates:true,cellStyles:true}),sourceSheet=sourceBook.Sheets[template.sheetName],cloneStyle=(cell:XLSX.CellObject|undefined)=>cell?.s?JSON.parse(JSON.stringify(cell.s)):undefined;ws["!merges"]=merges;ws["!cols"]=[{wch:6},{wch:18},{wch:16},{wch:38},{wch:20},{wch:48},{wch:16},{wch:11},{wch:20},{wch:23},{wch:46}];ws["!rows"]=rows.map((_,i)=>({hpt:i===0?28:i===1?34:i>=noteRow?26:24}));
  const titleSource=Object.keys(sourceSheet).find(a=>!a.startsWith("!")&&XLSX.utils.decode_cell(a).r===0&&clean(sourceSheet[a]?.v));if(ws.A1&&titleSource)ws.A1.s=cloneStyle(sourceSheet[titleSource]);for(let c=0;c<11;c++){const headerAddress=XLSX.utils.encode_cell({r:1,c}),sourceHeader=XLSX.utils.encode_cell({r:template.headerRow,c}),dataStyle=cloneStyle(sourceSheet[XLSX.utils.encode_cell({r:template.headerRow+3,c})]);if(ws[headerAddress])ws[headerAddress].s=cloneStyle(sourceSheet[sourceHeader]);for(let r=2;r<totalRow;r++){const a=XLSX.utils.encode_cell({r,c});if(ws[a]&&dataStyle)ws[a].s=JSON.parse(JSON.stringify(dataStyle))}}
  for(let r=2;r<totalRow;r++){const j=ws[XLSX.utils.encode_cell({r,c:9})];if(j&&j.v instanceof Date)j.z="dd/mm/yyyy"}
  const totalCell=ws[XLSX.utils.encode_cell({r:totalRow,c:7})];if(totalCell){totalCell.v=total;delete totalCell.f;totalCell.t="n"}
  const wb=XLSX.utils.book_new();XLSX.utils.book_append_sheet(wb,ws,template.sheetName.slice(0,31)||"TONG_HOP");
  const label=(decisions[0]?.className||decisions[0]?.major||"DAO_TAO").normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/đ/gi,"D").replace(/[^A-Za-z0-9]+/g,"_").replace(/^_|_$/g,"").toUpperCase();
  XLSX.writeFile(wb,`TONG_HOP_QUAN_LY_DAO_TAO_${label||"KET_QUA"}.xlsx`,{cellDates:true,cellStyles:true});
 }
 return <div className="min-h-screen bg-[#f3f7fb] text-[#17324d]">
  <header className="sticky top-0 z-30 border-b border-[#dce7f1] bg-white/95"><div className="mx-auto flex h-16 max-w-[1600px] items-center gap-4 px-4 lg:px-7"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-[#0e5cab] text-white shadow-lg"><GraduationCap size={23}/></div><div><div className="text-lg font-extrabold text-[#103f70]">HPOLC</div><div className="hidden text-xs text-[#70859a] sm:block">Hệ thống quản lý đào tạo · Bản xuất Excel 2.1</div></div></div><label className="ml-auto hidden max-w-md flex-1 items-center rounded-xl border border-[#d9e4ee] bg-[#f7fafd] px-3 md:flex"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} className="w-full bg-transparent px-2.5 py-2 text-sm outline-none" placeholder="Tìm số quyết định..."/></label><button className="rounded-xl border p-2.5"><Settings size={19}/></button><div className="grid h-9 w-9 place-items-center rounded-full bg-[#e4f0fb] text-sm font-bold text-[#0e5cab]">HP</div></div></header>
  <div className="mx-auto grid max-w-[1600px] lg:grid-cols-[230px_1fr]"><aside className="hidden min-h-[calc(100vh-64px)] border-r bg-white p-4 lg:block"><nav className="space-y-1.5"><Nav active icon={<LayoutDashboard/>} text="Tổng quan"/><Nav icon={<UploadCloud/>} text="Nhập dữ liệu"/><Nav icon={<FileText/>} text="Quyết định" badge={String(pdfs.length)}/><Nav icon={<Users/>} text="Sinh viên" badge={String(total)}/><Nav icon={<ShieldCheck/>} text="Đối soát" badge={String(decisions.filter(d=>d.note).length)} warn/><Nav icon={<BarChart3/>} text="Báo cáo"/></nav><div className="mt-8 rounded-2xl bg-[#eef7ff] p-4"><div className="mb-2 flex items-center gap-2 text-sm font-bold text-[#0e5cab]"><Sparkles size={16}/> Chuẩn dữ liệu</div><p className="text-xs leading-5 text-[#617a91]">Đọc nội dung trong quyết định, không suy đoán từ tên tệp.</p></div></aside>
   <main className="min-w-0 p-4 sm:p-6 lg:p-8"><div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-1 text-sm font-bold text-[#0e73b9]">TỔNG HỢP THEO FILE EXCEL MẪU</p><h1 className="text-2xl font-extrabold text-[#173f66] sm:text-3xl">Tổng hợp quản lý đào tạo</h1><p className="mt-1 text-sm text-[#6c8296]">Tự động đọc quyết định và xuất bảng chuẩn A–K</p></div><button onClick={exportExcel} disabled={!template||!decisions.length} className="flex items-center gap-2 rounded-xl bg-[#0e5cab] px-4 py-2.5 text-sm font-bold text-white shadow-lg disabled:opacity-40"><Download size={18}/> Xuất Excel theo mẫu chuẩn</button></div>
    {error&&<div className="mb-4 flex gap-2 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700"><AlertTriangle size={18}/>{error}</div>}
    <section className="mb-6 grid gap-4 xl:grid-cols-[1.25fr_.75fr]"><div className="rounded-2xl border bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-bold text-[#244c70]">Nhập tài liệu</h2><p className="mt-0.5 text-sm text-[#71879b]">Excel mẫu và các PDF quyết định trúng tuyển</p></div><span className="rounded-full bg-[#edf6ff] px-3 py-1 text-xs font-bold text-[#0e66ad]">Bảo mật trong phiên</span></div><div className="grid gap-3 sm:grid-cols-2"><UploadCard onClick={()=>excelRef.current?.click()} icon={<FileSpreadsheet/>} tone="green" title={template?.name||"Chọn Excel mẫu"} note=".xlsx hoặc .xls"/><UploadCard onClick={()=>pdfRef.current?.click()} icon={<FolderOpen/>} tone="orange" title={pdfs.length?`${pdfs.length} quyết định đã chọn`:"Chọn các quyết định PDF"} note="Có thể chọn 1 hoặc nhiều tệp"/></div><input ref={excelRef} hidden type="file" accept=".xlsx,.xls" onChange={e=>chooseExcel(e.target.files?.[0])}/><input ref={pdfRef} hidden type="file" accept="application/pdf" multiple onChange={e=>{setPdfs(Array.from(e.target.files||[]));setDecisions([])}}/>{(template||pdfs.length>0)&&<div className="mt-3 flex flex-wrap gap-2 text-xs text-[#60798f]">{template&&<Pill name={template.name} remove={()=>setTemplate(null)}/>} {pdfs.slice(0,2).map((f,i)=><Pill key={f.name+i} name={f.name} remove={()=>setPdfs(pdfs.filter((_,j)=>j!==i))}/>)} {pdfs.length>2&&<span>+{pdfs.length-2} tệp khác</span>}</div>}<div className="mt-4 flex items-center justify-between gap-3 border-t pt-4"><p className="text-xs leading-5 text-[#758a9c]">{busy?progress:"Tên file có thể bất kỳ; hệ thống đọc nội dung từng quyết định."}</p><button onClick={analyze} disabled={busy||!template||!pdfs.length} className="inline-flex shrink-0 items-center gap-2 rounded-xl bg-[#12a37f] px-4 py-2.5 text-sm font-bold text-white disabled:opacity-40">{busy&&<Loader2 className="animate-spin" size={16}/>} {busy?"Đang phân tích...":"Phân tích dữ liệu"}</button></div></div>
     <div className="rounded-2xl bg-gradient-to-br from-[#0d579f] to-[#087cad] p-5 text-white shadow-xl"><div className="flex items-start justify-between"><div><p className="text-sm font-semibold text-[#cceaff]">TỔNG SỐ SINH VIÊN</p><p className="mt-2 text-5xl font-extrabold">{total}</p></div><span className="grid h-12 w-12 place-items-center rounded-2xl bg-white/15"><Users/></span></div><div className="mt-7 h-2 rounded-full bg-white/15"><div className={`h-full rounded-full bg-[#53ddae] ${decisions.length?"w-full":"w-0"}`}/></div><div className="mt-3 flex justify-between text-sm"><span>{pdfs.length} quyết định · {decisions.length} danh sách</span><span className="flex items-center gap-1 font-bold"><Check size={16}/> {decisions.length?"Đã phân tích":"Chờ dữ liệu"}</span></div><div className="mt-5 grid grid-cols-3 border-t border-white/20 pt-4 text-center"><Mini n={String(groupTotals[0])} text="Đại học"/><Mini n={String(groupTotals[4])} text="TCKN"/><Mini n={String(groupTotals[5])} text="THPT"/></div></div></section>
    <section className="mb-6 grid grid-cols-2 gap-3 sm:grid-cols-3 xl:grid-cols-6">{GROUP_NAMES.map((n,i)=><div key={n} className="rounded-2xl border bg-white p-4"><div className="mb-3 h-1.5 w-9 rounded-full" style={{background:GROUP_COLORS[i]}}/><div className="text-2xl font-extrabold text-[#234a6d]">{groupTotals[i]}</div><div className="mt-1 text-sm font-semibold text-[#71879b]">{n}</div></div>)}</section>
    <section className="overflow-hidden rounded-2xl border bg-white shadow-sm"><div className="flex flex-wrap items-center justify-between gap-3 border-b px-5 py-4"><div><h2 className="font-bold text-[#244c70]">Đối soát quyết định</h2><p className="mt-0.5 text-sm text-[#778b9c]">Mỗi PDF có thể chứa một hoặc nhiều danh sách/lớp</p></div><button className="flex items-center gap-2 rounded-lg border px-3 py-2 text-sm font-semibold">Tất cả trạng thái <ChevronDown size={15}/></button></div><div className="overflow-x-auto"><table className="w-full min-w-[920px] text-left text-sm"><thead className="bg-[#f5f9fc] text-xs uppercase text-[#668097]"><tr><th className="px-5 py-3.5">Quyết định</th><th>Ngày</th><th>Loại tuyển</th><th>Lớp/Trạm</th><th className="text-center">Danh sách</th><th className="text-center">Tổng kiểm tra</th><th>Kết quả</th></tr></thead><tbody className="divide-y">{filtered.map(d=>{const checked=Object.values(d.groups).reduce((a,b)=>a+b,0);return <tr key={d.file} className="hover:bg-[#f8fbfd]"><td className="px-5 py-4 font-bold text-[#225985]">{d.id||"Chưa nhận diện"}</td><td>{d.date||"—"}</td><td>{d.type}</td><td className="max-w-72 py-3"><b>{d.className||"Chưa nhận diện lớp"}</b><span className="block truncate text-xs text-[#71879b]">{d.station||d.file}</span></td><td className="text-center font-bold">{d.students??0} SV</td><td className="text-center font-bold">{checked} SV</td><td>{d.note?<Status warn/>:<Status/>}</td></tr>})}</tbody></table></div><div className="flex flex-wrap items-center justify-between gap-3 border-t bg-[#fbfdff] px-5 py-4"><p className="text-sm text-[#688196]">Đã đọc <b>{pdfs.length} quyết định</b> và tách <b>{decisions.length} danh sách/lớp</b></p>{decisions.some(d=>d.note)&&<div className="flex items-center gap-2 rounded-lg bg-[#fff5e7] px-3 py-2 text-xs font-semibold text-[#9b610d]"><AlertTriangle size={15}/> Có dữ liệu cần kiểm tra trước khi xuất</div>}</div></section>
   </main></div>
 </div>}
function Nav({icon,text,active,badge,warn}:{icon:React.ReactElement,text:string,active?:boolean,badge?:string,warn?:boolean}){return <button className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold ${active?"bg-[#eaf4fd] text-[#0e5cab]":"text-[#637b90] hover:bg-[#f4f8fb]"}`}>{icon}<span>{text}</span>{badge&&<span className={`ml-auto rounded-full px-2 py-.5 text-xs ${warn?"bg-[#fff0dc] text-[#b36809]":"bg-[#eef3f7]"}`}>{badge}</span>}</button>}
function UploadCard({onClick,icon,title,note,tone}:{onClick:()=>void,icon:React.ReactNode,title:string,note:string,tone:string}){return <button onClick={onClick} className="flex min-h-28 items-center gap-4 rounded-xl border border-dashed border-[#b9cddd] bg-[#f8fbfe] p-4 text-left hover:border-[#0e73b9]"><span className={`grid h-11 w-11 place-items-center rounded-xl ${tone==="green"?"bg-[#e7f5ed] text-[#138452]":"bg-[#fff0eb] text-[#df5f32]"}`}>{icon}</span><span className="min-w-0"><b className="block truncate text-sm text-[#284d6d]">{title}</b><span className="mt-1 block text-xs text-[#7890a4]">{note}</span></span></button>}
function Pill({name,remove}:{name:string,remove:()=>void}){return <span className="inline-flex max-w-60 items-center gap-1 rounded-full bg-[#eef4f8] px-2.5 py-1"><span className="truncate">{name}</span><button onClick={remove}><X size={13}/></button></span>}
function Mini({n,text}:{n:string,text:string}){return <div><div className="text-xl font-extrabold">{n}</div><div className="text-xs text-[#cce7f6]">{text}</div></div>}
function Status({warn}:{warn?:boolean}){return warn?<span className="inline-flex items-center gap-1 rounded-full bg-[#fff3df] px-2.5 py-1 text-xs font-bold text-[#a96206]"><AlertTriangle size={13}/>Có lưu ý</span>:<span className="inline-flex items-center gap-1 rounded-full bg-[#e8f8f1] px-2.5 py-1 text-xs font-bold text-[#087a59]"><Check size={13}/>Khớp dữ liệu</span>}
